# Generated by Django 3.0.3 on 2021-12-23 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone

from datetime import timedelta

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_code', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expire_at', models.DateTimeField(default=lambda: timezone.now() + timedelta(minutes=5))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
